//! LVGL 9.x C generation for the LumaUI compiler.
//!
//! Output is intentionally deterministic and ordered so generated files diff
//! cleanly across runs. Generation walks the IR widget tree once per screen
//! and emits a header + implementation pair plus stable lifecycle hooks.

use lumaui_ir::{AppliedStyles, HexColor, Project, Screen, Widget, WidgetKind};
use std::fmt::Write as _;

const BODY_INDENT: &str = "  ";
const CONTINUATION_INDENT: &str = "                      ";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    pub path: String,
    pub contents: String,
}

pub fn generate_files(project: &Project) -> Vec<GeneratedFile> {
    let mut out = Vec::new();
    for screen in &project.screens {
        let slug = slugify(&screen.name);
        let create_fn = format!("{}screen_{slug}_create", project.symbol_prefix);
        out.push(generate_header(&create_fn, &slug));
        out.push(generate_source(project, screen, &create_fn, &slug));
    }
    out
}

fn generate_header(create_fn: &str, slug: &str) -> GeneratedFile {
    let guard = format!("LUMAUI_SCREEN_{}_GEN_H", slug.to_uppercase());
    let mut contents = String::new();
    writeln!(contents, "/* lumaui-region: compiler-owned begin */").unwrap();
    writeln!(contents, "/* Generated by LumaUI. Do not edit by hand. */").unwrap();
    writeln!(contents, "#ifndef {guard}").unwrap();
    writeln!(contents, "#define {guard}").unwrap();
    writeln!(contents).unwrap();
    writeln!(contents, "#include \"lvgl.h\"").unwrap();
    writeln!(contents).unwrap();
    writeln!(contents, "lv_obj_t *{create_fn}(lv_obj_t *parent);").unwrap();
    writeln!(contents).unwrap();
    writeln!(contents, "#endif /* {guard} */").unwrap();
    writeln!(contents, "/* lumaui-region: compiler-owned end */").unwrap();
    GeneratedFile {
        path: format!("screens/{slug}_gen.h"),
        contents,
    }
}

fn generate_source(
    project: &Project,
    screen: &Screen,
    create_fn: &str,
    slug: &str,
) -> GeneratedFile {
    let mut emit = SourceEmitter::new(project);
    emit.write_prologue(create_fn, slug);

    // Root: always create against the supplied parent.
    let root_var = emit.fresh_var(screen.root.kind);
    emit.line(format!("{BODY_INDENT}lv_obj_t *{root_var} = lv_obj_create(parent);"));
    emit.apply_layout(&root_var, &screen.root);
    emit.apply_styles(&root_var, &screen.root.applied_styles);
    emit.attach_event(&root_var, &screen.root);

    for child in &screen.root.children {
        emit.emit_widget(&root_var, child);
    }

    emit.line(format!("{BODY_INDENT}return {root_var};"));
    emit.line("}".into());
    emit.write_epilogue();

    GeneratedFile {
        path: format!("screens/{slug}_gen.c"),
        contents: emit.into_string(),
    }
}

struct SourceEmitter<'a> {
    project: &'a Project,
    body: String,
    counter: u32,
}

impl<'a> SourceEmitter<'a> {
    fn new(project: &'a Project) -> Self {
        Self {
            project,
            body: String::new(),
            counter: 0,
        }
    }

    fn write_prologue(&mut self, create_fn: &str, slug: &str) {
        writeln!(self.body, "/* lumaui-region: compiler-owned begin */").unwrap();
        writeln!(self.body, "/* Generated by LumaUI. Do not edit by hand. */").unwrap();
        writeln!(self.body, "#include \"{slug}_gen.h\"").unwrap();
        writeln!(self.body).unwrap();
        writeln!(self.body, "lv_obj_t *{create_fn}(lv_obj_t *parent) {{").unwrap();
    }

    fn write_epilogue(&mut self) {
        writeln!(self.body, "/* lumaui-region: compiler-owned end */").unwrap();
    }

    fn into_string(self) -> String {
        self.body
    }

    fn line(&mut self, line: String) {
        self.body.push_str(&line);
        self.body.push('\n');
    }

    fn fresh_var(&mut self, kind: WidgetKind) -> String {
        self.counter += 1;
        format!("{}_{}", kind_var_root(kind), self.counter)
    }

    fn emit_widget(&mut self, parent_var: &str, widget: &Widget) {
        let var = self.fresh_var(widget.kind);
        match widget.kind {
            WidgetKind::Screen => {
                // Screens only appear at the document root; nested Screens are
                // rejected at the semantic stage.
                self.line(format!(
                    "{BODY_INDENT}lv_obj_t *{var} = lv_obj_create({parent_var});"
                ));
            }
            WidgetKind::Column | WidgetKind::Row => {
                self.line(format!(
                    "{BODY_INDENT}lv_obj_t *{var} = lv_obj_create({parent_var});"
                ));
            }
            WidgetKind::Text => {
                self.line(format!(
                    "{BODY_INDENT}lv_obj_t *{var} = lv_label_create({parent_var});"
                ));
                if let Some(text) = &widget.text {
                    self.line(format!(
                        "{BODY_INDENT}lv_label_set_text({var}, {});",
                        c_string_literal(text)
                    ));
                }
            }
            WidgetKind::Button => {
                self.line(format!(
                    "{BODY_INDENT}lv_obj_t *{var} = lv_button_create({parent_var});"
                ));
            }
        }

        self.apply_layout(&var, widget);
        self.apply_styles(&var, &widget.applied_styles);
        self.attach_event(&var, widget);

        for child in &widget.children {
            self.emit_widget(&var, child);
        }
    }

    fn apply_layout(&mut self, var: &str, widget: &Widget) {
        match widget.kind {
            WidgetKind::Column => {
                self.line(format!(
                    "{BODY_INDENT}lv_obj_set_flex_flow({var}, LV_FLEX_FLOW_COLUMN);"
                ));
            }
            WidgetKind::Row => {
                self.line(format!(
                    "{BODY_INDENT}lv_obj_set_flex_flow({var}, LV_FLEX_FLOW_ROW);"
                ));
            }
            _ => {}
        }
    }

    fn apply_styles(&mut self, var: &str, styles: &AppliedStyles) {
        if styles.is_empty() {
            return;
        }
        if let Some(p) = styles.padding {
            self.line(format!(
                "{BODY_INDENT}lv_obj_set_style_pad_all({var}, {p}, LV_PART_MAIN);"
            ));
        }
        if let Some(w) = styles.width {
            self.line(format!("{BODY_INDENT}lv_obj_set_width({var}, {w});"));
        }
        if let Some(h) = styles.height {
            self.line(format!("{BODY_INDENT}lv_obj_set_height({var}, {h});"));
        }
        if let Some(bg) = &styles.background_color {
            self.line(format!(
                "{BODY_INDENT}lv_obj_set_style_bg_color({var}, lv_color_hex({}), LV_PART_MAIN);",
                bg.lvgl_hex_literal()
            ));
            self.line(format!(
                "{BODY_INDENT}lv_obj_set_style_bg_opa({var}, LV_OPA_COVER, LV_PART_MAIN);"
            ));
        }
        if let Some(tc) = &styles.text_color {
            self.line(format!(
                "{BODY_INDENT}lv_obj_set_style_text_color({var}, lv_color_hex({}), LV_PART_MAIN);",
                tc.lvgl_hex_literal()
            ));
        }
    }

    fn attach_event(&mut self, var: &str, widget: &Widget) {
        let Some(handler) = &widget.event_press else {
            return;
        };
        let prefix = &self.project.symbol_prefix;
        self.line(format!(
            "{BODY_INDENT}/* TODO(user): provide `void {prefix}event_{handler}(lv_event_t *e);` */"
        ));
        self.line(format!(
            "{BODY_INDENT}lv_obj_add_event_cb({var}, {prefix}event_{handler}, LV_EVENT_CLICKED,"
        ));
        self.line(format!("{CONTINUATION_INDENT}NULL);"));
    }
}

fn kind_var_root(kind: WidgetKind) -> &'static str {
    match kind {
        WidgetKind::Screen => "screen",
        WidgetKind::Column => "column",
        WidgetKind::Row => "row",
        WidgetKind::Text => "label",
        WidgetKind::Button => "btn",
    }
}

fn c_string_literal(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\x{:02x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn slugify(name: &str) -> String {
    let mut out = String::new();
    let mut last_underscore = false;
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            for lower in c.to_lowercase() {
                out.push(lower);
            }
            last_underscore = false;
        } else if !last_underscore {
            out.push('_');
            last_underscore = true;
        }
    }
    let trimmed = out.trim_matches('_');
    if trimmed.is_empty() {
        "screen".into()
    } else {
        trimmed.to_string()
    }
}

// The `_` field on `HexColor` should compile under `cargo test` even when no
// reader exercises it directly.
#[allow(dead_code)]
fn _hex_smoke(h: HexColor) -> String {
    h.lvgl_hex_literal()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn slugify_basic() {
        assert_eq!(slugify("home"), "home");
        assert_eq!(slugify("Home Page"), "home_page");
        assert_eq!(slugify("___"), "screen");
    }

    #[test]
    fn c_string_escapes_quote_and_backslash() {
        assert_eq!(c_string_literal("hi"), "\"hi\"");
        assert_eq!(c_string_literal("a\"b"), "\"a\\\"b\"");
        assert_eq!(c_string_literal("a\\b"), "\"a\\\\b\"");
    }
}
