/* lumaui-region: compiler-owned begin */
/* Generated by LumaUI. Do not edit by hand. */
#ifndef LUMAUI_SCREEN_HOME_GEN_H
#define LUMAUI_SCREEN_HOME_GEN_H

#include "lvgl.h"

lv_obj_t *lumaui_screen_home_create(lv_obj_t *parent);

#endif /* LUMAUI_SCREEN_HOME_GEN_H */
/* lumaui-region: compiler-owned end */
