/* lumaui-region: compiler-owned begin */
/* Generated by LumaUI. Do not edit by hand. */
#include "home_gen.h"

lv_obj_t *lumaui_screen_home_create(lv_obj_t *parent) {
    lv_obj_t *screen_1 = lv_obj_create(parent);
    lv_obj_t *column_2 = lv_obj_create(screen_1);
    lv_obj_set_flex_flow(column_2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_all(column_2, 16, LV_PART_MAIN);
    lv_obj_set_style_bg_color(column_2, lv_color_hex(0x20242b), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(column_2, LV_OPA_COVER, LV_PART_MAIN);
    lv_obj_t *label_3 = lv_label_create(column_2);
    lv_label_set_text(label_3, "Hello LumaUI");
    lv_obj_set_style_text_color(label_3, lv_color_hex(0xf5f7fa), LV_PART_MAIN);
    lv_obj_t *btn_4 = lv_btn_create(column_2);
    /* TODO(user): provide `void lumaui_event_open_settings(lv_event_t *e);` */
    lv_obj_add_event_cb(btn_4, lumaui_event_open_settings, LV_EVENT_CLICKED, NULL);
    lv_obj_t *label_5 = lv_label_create(btn_4);
    lv_label_set_text(label_5, "Settings");
    return screen_1;
}
/* lumaui-region: compiler-owned end */
